language: go
go:
  - 1.4.2

sudo: false

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint

install: true

script:
  - go vet -x ./...
  - $HOME/gopath/bin/golint ./...
  - go run .tools/dco.go
  
